import React from "react"
import './post.scss'


export const Post = () => {

    return(
        <div className = "postContainer" >
            <h1 className = "postTitle"> Why React? </h1>
            <p className="posts">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In egestas commodo neque, quis pretium nisi venenatis at. Phasellus volutpat nunc in sem dapibus faucibus. Nullam sodales felis quis tortor mattis dignissim. Aenean ac quam diam. In hac habitasse platea dictumst. Nulla facilisi. Nullam consectetur felis hendrerit lacus suscipit consectetur sit amet non est. Cras et lobortis eros. Quisque eget tortor nec ipsum condimentum fermentum eu non dolor. Sed est nunc, tincidunt et laoreet sed, hendrerit vel risus. Nullam dapibus lobortis ligula, nec condimentum arcu vehicula eget. Duis elementum, mauris quis sollicitudin vestibulum, eros magna vehicula sem, nec vehicula mauris nibh id risus. Fusce dapibus vestibulum nisi et convallis. In ac fringilla odio. Integer felis nulla, elementum id ornare in, convallis at libero. Aliquam id tempor neque.

Mauris ultricies neque et ullamcorper aliquam. Donec sagittis leo ac nisl maximus, quis venenatis tortor tempus. Proin maximus commodo lorem, a tincidunt risus faucibus id. Integer justo ante, tristique id sodales sit amet, scelerisque at tortor. Nunc molestie lectus sed tempor blandit. Nunc vehicula eros vel lacus tincidunt sodales. Integer a mi vestibulum, dictum sapien sit amet, aliquet lorem. Curabitur nec arcu in leo malesuada condimentum. Phasellus a iaculis metus. Ut nisi mauris, accumsan id vestibulum vel, lacinia eget diam. Phasellus tincidunt odio metus, sed malesuada tortor ullamcorper ut. Quisque efficitur ex ante, quis viverra metus placerat eget. Suspendisse aliquet lacus maximus dignissim fringilla. Nullam ut bibendum justo. Duis laoreet leo vel mi ultrices dapibus.

Pellentesque ornare sapien a lectus facilisis, cursus feugiat eros faucibus. Donec et nibh vitae nisl ultricies malesuada ut et sem. In viverra nibh erat, ut varius orci pharetra sollicitudin. Proin vitae blandit velit. Nulla interdum enim et erat pellentesque blandit. Maecenas rutrum sem aliquet eros aliquet, malesuada ornare nisl luctus. Nam pulvinar sapien vitae leo egestas, eu imperdiet purus aliquam. Praesent id magna et erat vestibulum ultrices. Pellentesque a neque ac felis tempus efficitur. Ut luctus, libero eu dictum sodales, elit purus fermentum leo, non pharetra massa nunc eget ligula. Sed vitae dictum urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut facilisis iaculis felis, sit amet condimentum lacus maximus vel. Praesent quis lacus magna. Sed fringilla nisi sit amet ipsum bibendum malesuada.

Morbi ex ligula, pellentesque ac nisl vitae, vestibulum porttitor felis. Etiam nec massa non augue commodo tincidunt. Pellentesque suscipit pellentesque neque eget pulvinar. Nullam id congue purus, at fermentum tellus. Duis sodales, urna id ultrices cursus, felis erat congue arcu, ac pharetra ex mi ac orci. Phasellus non est commodo, efficitur sem ut, dictum augue. Integer lacus nulla, auctor gravida libero id, finibus convallis orci. Maecenas maximus pharetra mauris, in dapibus magna tincidunt quis. Phasellus nibh nulla, tempus ac pulvinar non, hendrerit eu magna. Aenean vitae est vitae dui mattis laoreet nec a mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus iaculis dui eu felis blandit lobortis. Phasellus vitae vehicula odio, sit amet ultrices risus. Cras posuere metus lorem, ut sodales purus tempus sed. Vestibulum mattis augue at justo feugiat, non tristique dolor posuere. Fusce a lectus cursus dolor blandit volutpat quis at erat.

Fusce in finibus lacus. Quisque ut ultricies sem, non posuere nunc. Sed et accumsan eros, eu maximus lacus. Vivamus luctus velit vel varius auctor. Ut a consectetur metus. Donec sit amet dolor in lacus vulputate molestie sed sed libero. Morbi neque ante, semper ac gravida at, finibus convallis massa. Quisque rhoncus, lorem vitae convallis interdum, neque mi lacinia ligula, id tincidunt orci felis eget erat. Sed sodales aliquam diam, vel consectetur lorem. Ut mattis condimentum cursus. Suspendisse nunc tortor, cursus eget risus eu, eleifend cursus elit. Mauris a purus suscipit, consequat elit at, congue nunc. Maecenas sit amet augue congue, placerat orci aliquet, rhoncus massa.</p>
        </div>
    )
} 